smageseq_config = {
    "encoder_dim": [[256, 64], [256, 64]],
    "decoder_dim": [[64, 256], [64, 256]],
    "discriminator_dim": [[256, 64, 32], [256, 64, 32]],
    "hidden_dim": 32,
    "activation1": 'relu',
    "activation2": 'leakyrelu',
    "PBMC10K_Params": {"pretrain_epochs": 100,
                        "train_epochs": 200,
                        "batch_size": 256,
                        "cutoff": 0.5,
                        "lr_ae": 0.0005,
                        "lr_d": 0.003,
                        "alpha": 1.0,
                        "beta": 0.5,
                        "sigma": 1.0,
                        "gamma": 1.0,
                        "zeta_1": 0.005,
                        "zeta_2": 0.003,
                        "noise_sigma": [2.5, 2.5],
                        "phi_1": 0.005,
                        "phi_2": 0.005,
                        "data_preprocess": [True, True, 2000, 2000]},
    "use_indicator": False  # default setting
}